### ISSUE TITLE
连续发送问题

### ISSUE THREAD

**Issue by liuwf2015** [Guanges/TransPortEngine#1]
您好，非常感谢您的代码分享。但是遇到一个问题：连接快速发送数据时，连丢失。请问如何解决呢？

**Comment by Guanges** [comment]
是数据丢失 ，还是连接丢失

**Comment by liuwf2015** [comment]
连续发送会导致，数据丢失



&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 刘文非
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 18022884107


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guanges/TransPortEngine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 下午2:47
收件人:&nbsp;"Guanges/TransPortEngine"<TransPortEngine@noreply.github.com&gt;;
抄送:&nbsp;"刘文非"<80377362@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Guanges/TransPortEngine] 连续发送问题 (#1)





 
是数据丢失 ，还是连接丢失

**Comment by Guanges** [comment]
是不是server和client有头和无头混用了

**Comment by liuwf2015** [comment]
不是啊，我都是用无头的。server&nbsp;端与&nbsp;client端一样



&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 刘文非
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 18022884107


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guanges/TransPortEngine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 下午3:10
收件人:&nbsp;"Guanges/TransPortEngine"<TransPortEngine@noreply.github.com&gt;;
抄送:&nbsp;"刘文非"<80377362@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Guanges/TransPortEngine] 连续发送问题 (#1)





 
是不是server和client有头和无头混用了

**Comment by Guanges** [comment]
https://github.com/Guanges/TransPortEngine/commit/51d8701d7f038c51cf7d7214cddc26f8727eeef6
可以试一下这个 commit 有没有解决
